# Generated by Django 3.1.3 on 2020-11-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vrtic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=128, verbose_name='Naziv vrtića')),
                ('adresa', models.CharField(max_length=128, verbose_name='Adresa')),
                ('kontakt_broj', models.CharField(max_length=16, verbose_name='Kontakt broj')),
                ('kontakt_email', models.EmailField(max_length=254, verbose_name='Email kontakt')),
            ],
            options={
                'verbose_name': 'Vrtić',
                'verbose_name_plural': 'Vrtići',
            },
        ),
    ]
