# Generated by Django 3.1.3 on 2020-11-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogadjaji', '0001_initial'),
        ('vrtic', '0001_initial'),
        ('djeca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=128, verbose_name='Naziv tipa programa')),
                ('dodatni_boravak', models.BooleanField(verbose_name='Dostupnost dodatnog boravka')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programi',
            },
        ),
        migrations.CreateModel(
            name='RadnoVrijeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_smjene', models.CharField(max_length=64, verbose_name='Naziv smjene')),
                ('vrijeme_start', models.TimeField(verbose_name='Vrijeme početka')),
                ('vrijeme_kraj', models.TimeField(verbose_name='Vrijeme kraja')),
            ],
            options={
                'verbose_name': 'Radno vrijeme',
                'verbose_name_plural': 'Radna vremena',
            },
        ),
        migrations.CreateModel(
            name='VrstaPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=128, verbose_name='Naziv programa')),
                ('clanstvo_cijena', models.FloatField(help_text='Cijena mjesečne članarine', verbose_name='Cijena')),
                ('vrtic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrtic.vrtic', verbose_name='Vrtić')),
            ],
            options={
                'verbose_name': 'Vrsta programa',
                'verbose_name_plural': 'Vrste programa',
            },
        ),
        migrations.CreateModel(
            name='TipPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=128, verbose_name='Naziv tipa programa')),
                ('broj_sati', models.IntegerField(verbose_name='Broj sati')),
                ('max_broj_djece', models.IntegerField(verbose_name='Maksimalni broj djece')),
                ('dobne_skupine', models.ManyToManyField(to='djeca.DobnaSkupina', verbose_name='Dobne skupine')),
                ('dogadjaji', models.ManyToManyField(to='dogadjaji.Dogadjaj', verbose_name='Događaji')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programi.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Tip programa',
                'verbose_name_plural': 'Tipovi programa',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='radna_vremena',
            field=models.ManyToManyField(to='programi.RadnoVrijeme', verbose_name='Radna vremena'),
        ),
        migrations.AddField(
            model_name='program',
            name='vrsta_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programi.vrstaprograma', verbose_name='Vrsta programa'),
        ),
    ]
