# Generated by Django 3.1.3 on 2020-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='naziv',
            field=models.CharField(max_length=128, verbose_name='Naziv programa'),
        ),
    ]
