# Generated by Django 3.1.3 on 2020-12-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smjene', '0001_initial'),
        ('programi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='smjene',
            field=models.ManyToManyField(to='smjene.Smjena', verbose_name='Smjene'),
        ),
        migrations.AddField(
            model_name='program',
            name='vrsta_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programi.vrstaprograma', verbose_name='Vrsta programa'),
        ),
    ]
