# Generated by Django 3.1.3 on 2020-12-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0001_initial'),
        ('programi', '0002_auto_20201220_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipprograma',
            name='dogadjaji',
            field=models.ManyToManyField(blank=True, to='dogadjaji.Dogadjaj', verbose_name='Događaji'),
        ),
    ]
