# Generated by Django 3.1.3 on 2020-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeca', '0001_initial'),
        ('programi', '0003_program_opis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrstaprograma',
            name='dobne_skupine',
        ),
        migrations.AddField(
            model_name='program',
            name='dobne_skupine',
            field=models.ManyToManyField(to='djeca.DobnaSkupina', verbose_name='Dobne skupine'),
        ),
    ]
