# Generated by Django 3.1.3 on 2020-12-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smjene', '0001_initial'),
        ('programi', '0005_auto_20201230_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrstaprograma',
            name='smjene',
        ),
        migrations.AddField(
            model_name='program',
            name='smjene',
            field=models.ManyToManyField(to='smjene.Smjena', verbose_name='Smjene'),
        ),
    ]
