# Generated by Django 3.1.3 on 2021-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programi', '0006_auto_20201230_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrstaprograma',
            name='clanstvo_cijena',
            field=models.FloatField(help_text='Cijena članarine po satu programa', verbose_name='Cijena'),
        ),
    ]
