# Generated by Django 3.1.3 on 2021-02-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djeca', '0003_auto_20210107_0002'),
        ('dogadjaji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suglasnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odobren', models.BooleanField(help_text='Označite dajete li suglasnost za prisustvo djeteta u predstavi', verbose_name='Odobren')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
                ('dijete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djeca.dijete', verbose_name='Dijete')),
                ('dogadjaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogadjaji.dogadjaj', verbose_name='Dogadjaj')),
            ],
            options={
                'verbose_name': 'Suglasnost',
                'verbose_name_plural': 'Suglasnosti',
                'unique_together': {('dijete', 'dogadjaj')},
            },
        ),
    ]
