# Generated by Django 3.1.3 on 2021-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0002_suglasnost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suglasnost',
            name='odobren',
            field=models.BooleanField(default=False, help_text='Označite dajete li suglasnost za prisustvo djeteta u predstavi', verbose_name='Odobren'),
        ),
    ]
