# Generated by Django 3.1.3 on 2021-02-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0003_auto_20210202_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suglasnost',
            name='odobren',
            field=models.BooleanField(help_text='Označite dajete li suglasnost za prisustvo djeteta u predstavi', null=True, verbose_name='Odobren'),
        ),
    ]
