# Generated by Django 3.1.3 on 2021-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0004_auto_20210203_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suglasnost',
            name='odobren',
            field=models.BooleanField(help_text='Označite dajete li suglasnost za prisustvo djeteta u predstavi. Spremite neoznačeno ukoliko ne dajete suglasnost', null=True, verbose_name='Odobren'),
        ),
    ]
