# Generated by Django 3.1.3 on 2021-02-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0005_auto_20210205_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='datum_kraj',
            field=models.DateField(verbose_name='Datum završetka'),
        ),
        migrations.AlterField(
            model_name='dogadjaj',
            name='vrijeme_kraj',
            field=models.TimeField(verbose_name='Vrijeme završetka'),
        ),
    ]
