# Generated by Django 3.1.3 on 2020-12-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racuni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dijete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=64, verbose_name='Ime')),
                ('prezime', models.CharField(max_length=64, verbose_name='Prezime')),
                ('datum_rodjenja', models.DateField(verbose_name='Datum rođenja')),
                ('dodatne_informacije', models.TextField(verbose_name='Dodatne informacije')),
                ('roditelj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.racun', verbose_name='Roditelj')),
            ],
            options={
                'verbose_name': 'Dijete',
                'verbose_name_plural': 'Djeca',
            },
        ),
        migrations.CreateModel(
            name='DobnaSkupina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=128, verbose_name='Naziv')),
                ('godine_min', models.FloatField(help_text='Minimalna dob dijeteta u godinama', verbose_name='Donja granica - godine')),
                ('godine_max', models.FloatField(help_text='Maksimalna dob dijeteta u godinama', verbose_name='Gornja granica - godine')),
            ],
            options={
                'verbose_name': 'Dobna skupina',
                'verbose_name_plural': 'Dobne skupine',
            },
        ),
        migrations.CreateModel(
            name='DijeteNapredak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField(verbose_name='Komentar')),
                ('datum_start', models.DateField(verbose_name='Datum početka praćenja')),
                ('datum_kraj', models.DateField(verbose_name='Datum kraja praćenja')),
                ('ocjena', models.IntegerField(choices=[(1, 'Nedovoljan'), (2, 'Dovoljan'), (3, 'Dobar'), (4, 'Vrlo dobar'), (5, 'Odličan')], help_text='Ocjena djeteta u skali od 1 - 5', verbose_name='Ocjena')),
                ('dijete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djeca.dijete', verbose_name='Dijete')),
                ('djelatnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.racun', verbose_name='Djelatnik')),
            ],
            options={
                'verbose_name': 'Dijete - napredak',
                'verbose_name_plural': 'Djeca - napretci',
            },
        ),
    ]
