# Generated by Django 3.1.3 on 2020-11-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racuni', '0001_initial'),
        ('programi', '0001_initial'),
        ('djeca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dijetenapredak',
            name='djelatnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.djelatnik', verbose_name='Djelatnik'),
        ),
        migrations.AddField(
            model_name='dijete',
            name='roditelj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.roditelj', verbose_name='Roditelj'),
        ),
        migrations.AddField(
            model_name='dijete',
            name='tip_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programi.tipprograma', verbose_name='Program'),
        ),
    ]
