# Generated by Django 3.1.3 on 2021-02-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smjene', '0001_initial'),
        ('djeca', '0003_auto_20210107_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='dijete',
            name='smjena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smjene.smjena', verbose_name='Smjena čuvanja'),
        ),
    ]
