# Generated by Django 3.1.3 on 2020-12-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djeca', '0003_remove_dijete_tip_programa'),
        ('racuni', '0002_auto_20201219_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dijete',
            name='roditelj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.racun', verbose_name='Roditelj'),
        ),
        migrations.AlterField(
            model_name='dijetenapredak',
            name='djelatnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.racun', verbose_name='Djelatnik'),
        ),
    ]
