# Generated by Django 3.1.3 on 2020-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeca', '0004_auto_20201219_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dobnaskupina',
            name='godine_max',
        ),
        migrations.RemoveField(
            model_name='dobnaskupina',
            name='godine_min',
        ),
        migrations.AddField(
            model_name='dobnaskupina',
            name='mjeseci_max',
            field=models.FloatField(default=1, help_text='Maksimalna dob dijeteta u mjesecima', verbose_name='Gornja granica - mjeseci'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dobnaskupina',
            name='mjeseci_min',
            field=models.FloatField(default=0, help_text='Minimalna dob dijeteta u mjesecima', verbose_name='Donja granica - mjeseci'),
            preserve_default=False,
        ),
    ]
