# Generated by Django 3.1.3 on 2020-12-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeca', '0005_auto_20201220_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dobnaskupina',
            name='mjeseci_max',
        ),
        migrations.RemoveField(
            model_name='dobnaskupina',
            name='mjeseci_min',
        ),
        migrations.AddField(
            model_name='dobnaskupina',
            name='godine_max',
            field=models.FloatField(default=1, help_text='Maksimalna dob dijeteta u godinama', verbose_name='Gornja granica - godine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dobnaskupina',
            name='godine_min',
            field=models.FloatField(default=1, help_text='Minimalna dob dijeteta u godinama', verbose_name='Donja granica - godine'),
            preserve_default=False,
        ),
    ]
