# Generated by Django 3.1.3 on 2020-12-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roditelj_puno_ime', models.CharField(max_length=128, verbose_name='Ime i prezime')),
                ('roditelj_email', models.EmailField(max_length=254, verbose_name='Email adresa')),
                ('roditelj_datum_rodjenja', models.DateField(verbose_name='Datum rođenja')),
                ('roditelj_telefon', models.CharField(max_length=50, verbose_name='Telefon')),
                ('dijete_puno_ime', models.CharField(max_length=128, verbose_name='Ime i prezime')),
                ('dijete_datum_rodjenja', models.DateField(verbose_name='Datum rođenja')),
                ('dijete_dodatne_informacije', models.TextField(blank=True, null=True, verbose_name='Dodatne informacije')),
                ('odobren', models.BooleanField(default=None, null=True, verbose_name='Zahtjev odobren')),
                ('obrazlozenje', models.TextField(blank=True, verbose_name='Obrazloženje zahtjeva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
            ],
            options={
                'verbose_name': 'Upis',
                'verbose_name_plural': 'Upisi',
            },
        ),
    ]
