# Generated by Django 3.1.3 on 2020-12-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programi', '0003_program_opis'),
        ('upisi', '0002_upis_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upis',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programi.program', verbose_name='Program'),
        ),
    ]
