# Generated by Django 3.1.3 on 2021-02-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upisi', '0003_auto_20201228_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upis',
            name='roditelj_email',
            field=models.EmailField(help_text='Ovaj će se email koristiti za prijavu', max_length=254, verbose_name='Email adresa'),
        ),
    ]
