# Generated by Django 3.1.3 on 2021-02-03 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programi', '0006_auto_20201230_1310'),
        ('upisi', '0004_auto_20210202_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upis',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programi.program', verbose_name='Program'),
        ),
    ]
