# Generated by Django 3.1.3 on 2021-02-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smjene', '0001_initial'),
        ('upisi', '0005_auto_20210203_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='upis',
            name='smjena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smjene.smjena', verbose_name='Smjena'),
        ),
    ]
