# Generated by Django 3.1.3 on 2020-12-24 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipRacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=128, verbose_name='Naziv tipa')),
                ('satnica', models.FloatField(default=0, verbose_name='Satnica')),
            ],
            options={
                'verbose_name': 'Tip računa',
                'verbose_name_plural': 'Tipovi računa',
            },
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=16, verbose_name='Kontakt telefon')),
                ('datum_rodjenja', models.DateField(verbose_name='Datum rođenja')),
                ('je_roditelj', models.BooleanField(verbose_name='Roditelj')),
                ('je_djelatnik', models.BooleanField(verbose_name='Djelatnik')),
                ('je_voditelj', models.BooleanField(default=False, verbose_name='Voditelj')),
                ('je_strucni_tim', models.BooleanField(default=False, verbose_name='Pripada stručnom timu')),
                ('tip_racuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.tipracuna', verbose_name='Tip računa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Django korisnik')),
            ],
            options={
                'verbose_name': 'Račun',
                'verbose_name_plural': 'Računi',
            },
        ),
    ]
