# Generated by Django 3.1.3 on 2020-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=16, verbose_name='Kontakt telefon')),
                ('datum_rodjenja', models.DateField(verbose_name='Datum rođenja')),
            ],
            options={
                'verbose_name': 'Račun',
                'verbose_name_plural': 'Računi',
            },
        ),
        migrations.CreateModel(
            name='TipRacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=32, verbose_name='Naziv tipa')),
                ('je_roditelj', models.BooleanField(verbose_name='Roditelj')),
                ('je_djelatnik', models.BooleanField(verbose_name='Djelatnik')),
                ('je_voditelj', models.BooleanField(default=False, verbose_name='Voditelj')),
                ('je_strucni_tim', models.BooleanField(default=False, verbose_name='Pripada stručnom timu')),
            ],
            options={
                'verbose_name': 'Djelatnik',
                'verbose_name_plural': 'Djelatnici',
            },
        ),
        migrations.RemoveField(
            model_name='djelatnik',
            name='tip_djelatnika',
        ),
        migrations.RemoveField(
            model_name='djelatnik',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roditelj',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tipdjelatnika',
            name='tip_programa',
        ),
    ]
