# Generated by Django 3.1.3 on 2020-12-19 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programi', '0001_initial'),
        ('djeca', '0004_auto_20201219_2136'),
        ('racuni', '0002_auto_20201219_2136'),
        ('financije', '0002_auto_20201219_2136'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Djelatnik',
        ),
        migrations.DeleteModel(
            name='Roditelj',
        ),
        migrations.DeleteModel(
            name='TipDjelatnika',
        ),
        migrations.AddField(
            model_name='tipracuna',
            name='tip_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programi.tipprograma', verbose_name='Tip programa'),
        ),
        migrations.AddField(
            model_name='racun',
            name='tip_racuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.tipracuna', verbose_name='Tip računa'),
        ),
        migrations.AddField(
            model_name='racun',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Django korisnik'),
        ),
    ]
