# Generated by Django 3.1.3 on 2021-02-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0003_auto_20210203_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racun',
            name='je_djelatnik',
        ),
        migrations.RemoveField(
            model_name='racun',
            name='je_roditelj',
        ),
        migrations.RemoveField(
            model_name='racun',
            name='je_strucni_tim',
        ),
        migrations.RemoveField(
            model_name='racun',
            name='je_voditelj',
        ),
    ]
