# Generated by Django 3.1.3 on 2020-12-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0004_auto_20201220_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipracuna',
            name='naziv',
            field=models.CharField(max_length=128, verbose_name='Naziv tipa'),
        ),
    ]
