# Generated by Django 3.1.3 on 2021-02-03 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0004_auto_20210203_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='racun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum stvaranja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja'),
        ),
    ]
