# Generated by Django 3.1.3 on 2020-12-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0005_auto_20201220_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipracuna',
            name='je_djelatnik',
        ),
        migrations.RemoveField(
            model_name='tipracuna',
            name='je_roditelj',
        ),
        migrations.RemoveField(
            model_name='tipracuna',
            name='je_strucni_tim',
        ),
        migrations.RemoveField(
            model_name='tipracuna',
            name='je_voditelj',
        ),
        migrations.AddField(
            model_name='racun',
            name='je_djelatnik',
            field=models.BooleanField(default=True, verbose_name='Djelatnik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racun',
            name='je_roditelj',
            field=models.BooleanField(default=False, verbose_name='Roditelj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racun',
            name='je_strucni_tim',
            field=models.BooleanField(default=False, verbose_name='Pripada stručnom timu'),
        ),
        migrations.AddField(
            model_name='racun',
            name='je_voditelj',
            field=models.BooleanField(default=False, verbose_name='Voditelj'),
        ),
    ]
