# Generated by Django 3.1.3 on 2020-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programi', '0001_initial'),
        ('racuni', '0006_auto_20201220_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipracuna',
            name='placa',
            field=models.FloatField(default=1, verbose_name='Plaća'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tipracuna',
            name='tip_programa',
        ),
        migrations.AddField(
            model_name='tipracuna',
            name='tip_programa',
            field=models.ManyToManyField(to='programi.TipPrograma', verbose_name='Tipovi programa'),
        ),
    ]
