# Generated by Django 3.1.3 on 2020-12-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0008_auto_20201220_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roditelj_puno_ime', models.CharField(max_length=128, verbose_name='Ime i prezime')),
                ('roditelj_email', models.EmailField(max_length=254, verbose_name='Email adresa')),
                ('roditelj_datum_rodjenja', models.DateField(verbose_name='Datum rođenja')),
                ('roditelj_telefon', models.CharField(max_length=50, verbose_name='Telefon')),
                ('dijete_puno_ime', models.CharField(max_length=128, verbose_name='Ime i prezime')),
                ('dijete_datum_rodjenja', models.DateField(verbose_name='Datum rođenja')),
                ('odobren', models.BooleanField(verbose_name='Zahtjev odobren')),
                ('obrazlozenje', models.TextField(verbose_name='Obrazloženje zahtjeva')),
            ],
            options={
                'verbose_name': 'Upis',
                'verbose_name_plural': 'Upisi',
            },
        ),
    ]
