# Generated by Django 3.1.3 on 2020-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0009_upis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upis',
            name='obrazlozenje',
            field=models.TextField(blank=True, verbose_name='Obrazloženje zahtjeva'),
        ),
        migrations.AlterField(
            model_name='upis',
            name='odobren',
            field=models.BooleanField(default=False, verbose_name='Zahtjev odobren'),
        ),
    ]
