# Generated by Django 3.1.3 on 2020-12-20 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0010_auto_20201220_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='upis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum stvaranja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja'),
        ),
    ]
