# Generated by Django 3.1.3 on 2020-12-24 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racuni', '0001_initial'),
        ('programi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Smjena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_smjene', models.CharField(max_length=64, verbose_name='Naziv smjene')),
                ('vrijeme_start', models.TimeField(verbose_name='Vrijeme početka')),
                ('vrijeme_kraj', models.TimeField(verbose_name='Vrijeme kraja')),
            ],
            options={
                'verbose_name': 'Smjena',
                'verbose_name_plural': 'Smjene',
            },
        ),
        migrations.CreateModel(
            name='DjelatnikSmjenaProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vrijeme stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Vrijeme ažuriranja')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('djelatnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.racun', verbose_name='Djelatnik')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programi.program', verbose_name='Program')),
                ('smjena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smjene.smjena', verbose_name='Smjena')),
            ],
            options={
                'verbose_name': 'Djelatnik - smjena i program',
                'verbose_name_plural': 'Djelatnici - smjene i programi',
            },
        ),
    ]
