# Generated by Django 3.1.3 on 2020-12-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0002_auto_20201219_2136'),
        ('financije', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placadjelatnik',
            name='tip_djelatnika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.tipracuna', verbose_name='Tip djelatnika'),
        ),
    ]
