# Generated by Django 3.1.3 on 2021-02-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0005_auto_20210204_0013'),
        ('djeca', '0003_auto_20210107_0002'),
        ('financije', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clanarina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=128, verbose_name='Naziv dokumenta')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum dokumenta')),
                ('iznos', models.FloatField(verbose_name='Iznos')),
                ('PDV', models.FloatField(verbose_name='PDV')),
                ('ukupno', models.FloatField(verbose_name='Ukupno')),
                ('dijete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djeca.dijete', verbose_name='Dijete')),
            ],
            options={
                'verbose_name': 'Članarina',
                'verbose_name_plural': 'Članarine',
            },
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50, verbose_name='Naziv dokumenta')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum dokumenta')),
                ('bruto', models.FloatField(verbose_name='Bruto iznos plaće')),
                ('neto', models.FloatField(verbose_name='Neto iznos plaće')),
                ('djelatnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racuni.racun', verbose_name='Djelatnik')),
            ],
            options={
                'verbose_name': 'Plaća',
                'verbose_name_plural': 'Plaće',
            },
        ),
        migrations.RemoveField(
            model_name='racunclanarina',
            name='dijete',
        ),
        migrations.DeleteModel(
            name='PlacaDjelatnik',
        ),
        migrations.DeleteModel(
            name='RacunClanarina',
        ),
    ]
